-- Adicionar livros iniciais à loja
INSERT INTO public.produtos (nome, categoria, url_compra, ativo, created_at, updated_at)
VALUES
  ('O Guia Definitivo para Arquitetos e Engenheiros', 'livros', 'https://guiadefinitivo.com.br/', true, now(), now()),
  ('Projetos e Obras de Sucesso', 'livros', 'https://livro.boranaobra.com.br/projetoseobras/', true, now(), now()),
  ('O Mito do Empreendedor', 'livros', 'https://amzn.to/3mWndVB', true, now(), now()),
  ('Como Fazer Amigos e Influenciar Pessoas', 'livros', 'https://amzn.to/3ouTt2I', true, now(), now()),
  ('Pense e Enriqueça', 'livros', 'https://amzn.to/3T3VL5m', true, now(), now()),
  ('Pense Simples', 'livros', 'https://amzn.to/303NsAn', true, now(), now()),
  ('A Startup Enxuta', 'livros', 'https://amzn.to/3074mho', true, now(), now()),
  ('Scrum: A arte de fazer o dobro do trabalho na metade do tempo', 'livros', 'https://amzn.to/3Gk35DF', true, now(), now()),
  ('Os Sete Hábitos das Pessoas Altamente Eficazes', 'livros', 'https://amzn.to/3bWwg2A', true, now(), now()),
  ('Como Convencer Alguém em 90 Segundos', 'livros', 'https://amzn.to/3YRakM4', true, now(), now()),
  ('Detonando!', 'livros', 'https://www.amazon.com.br/Detonando-Dinheiro-Influ%C3%AAncia-Fortalecendo-Sociais/dp/8550804215?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2O33NMKB70CK9&keywords=detonando+do+Gary+vee&qid=1682440238&sprefix=detonando+do+gary+vee%2Caps%2C376&sr=8-1&ufe=app_do%3Aamzn1.fos.6121c6c4-c969-43ae-92f7-cc248fc6181d&linkCode=sl1&tag=bno01-20&linkId=0ae5d0f5e066a77b3d4213832039eaa6&ref_=as_li_ss_tl', true, now(), now()),
  ('Tribos: nós precisamos que você nos liderem', 'livros', 'https://www.amazon.com.br/Tribos-Seth-Godin/dp/8576088045?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1RHIGU967KZ05&keywords=tribos&qid=1682440294&sprefix=tribos%2Caps%2C179&sr=8-1-spons&ufe=app_do%3Aamzn1.fos.6121c6c4-c969-43ae-92f7-cc248fc6181d&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyMk9aRjhKOUFRN1kyJmVuY3J5cHRlZElkPUEwNjAxNjM2MUU5NlRFSVlOMkQ4ViZlbmNyeXB0ZWRBZElkPUEwMjAyNzY4SlowWklVNjMzUDE0JndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ%3D%3D&linkCode=sl1&tag=bno01-20&linkId=889df0bd42b762497fd62314a07438d9&ref_=as_li_ss_tl', true, now(), now()),
  ('Em Busca de Sentido', 'livros', 'https://amzn.to/3ZSEFuk', true, now(), now()),
  ('Pai Rico, Pai Pobre', 'livros', 'https://amzn.to/3q55NYm', true, now(), now()),
  ('Os Segredos da Mente Milionária', 'livros', 'https://amzn.to/3zABmMQ', true, now(), now()),
  ('O Jeito Disney de Encantar os Clientes', 'livros', 'https://amzn.to/3IuMI90', true, now(), now()),
  ('Responsabilidade Extrema', 'livros', 'https://amzn.to/3y5YAcT', true, now(), now()),
  ('A Única Coisa', 'livros', 'https://amzn.to/3klS9wK', true, now(), now()),
  ('Essencialismo', 'livros', 'https://amzn.to/3BINgJR', true, now(), now()),
  ('Isso é Marketing', 'livros', 'https://amzn.to/4h9r0J6', true, now(), now()),
  ('Storybrand', 'livros', 'https://amzn.to/489XVJB', true, now(), now()),
  ('Contágio', 'livros', 'https://amzn.to/3Y5vJmE', true, now(), now()),
  ('Imunidade Emocional', 'livros', 'http://imunidadeemocional.com.br/livro', true, now(), now()),
  ('O Poder do Hábito', 'livros', 'https://amzn.to/3U9TbxV', true, now(), now()),
  ('Avalie o que Importa', 'livros', 'https://amzn.to/4f3jVbl', true, now(), now()),
  ('O Estilo Startup', 'livros', 'https://amzn.to/3U8lRXO', true, now(), now()),
  ('O Paladar não Retrocede', 'livros', 'https://amzn.to/3NqG6w7', true, now(), now()),
  ('As Armas da Persuasão', 'livros', 'https://amzn.to/3YmNYVU', true, now(), now()),
  ('Os Segredos do Lobo', 'livros', 'https://amzn.to/3BMBjmg', true, now(), now()),
  ('Onze Anéis', 'livros', 'https://amzn.to/3BNGvGE', true, now(), now()),
  ('Onde os Sonhos Acontecem', 'livros', 'https://amzn.to/4f48zUy', true, now(), now()),
  ('Posicionamento', 'livros', 'https://amzn.to/3YqFihl', true, now(), now()),
  ('O Monge e o Executivo', 'livros', 'https://amzn.to/3A33P2y', true, now(), now()),
  ('12 Regras Para a Vida', 'livros', 'https://amzn.to/3NE1vSU', true, now(), now())
ON CONFLICT DO NOTHING;
